# Generated by Django 3.2.18 on 2023-05-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='media/images', verbose_name='Изображение')),
                ('alt', models.CharField(help_text='Добавьте описание изображения для использования в alt-атрибуте', max_length=100, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_name',
            field=models.CharField(max_length=60, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Выберите автора из списка', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hex_code',
            field=models.CharField(max_length=7, verbose_name='Цветовой код (hex)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-путь к данному тэгу'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.image'),
        ),
    ]
