# Generated by Django 4.2.1 on 2023-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(verbose_name="Время приготовления"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                help_text="Добавьте фото к рецепту",
                upload_to="recipes/images",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="recipes.tag", verbose_name="Теги"),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.PositiveSmallIntegerField(verbose_name="Количество"),
        ),
    ]
